name: B Reasor Photography
favicon: null
layout_spectrum: 0.5777220462914556
typography_spectrum: 0.29705249960534275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8414679861161858
  lightness: 0.6268195016309619
  saturation: 0.7202987936325371
  rhythmicContrast: 0.021666635759174824
purpose: []
